### ISSUE TITLE
Failed to generate the build

### ISSUE THREAD

**Issue by shreyasb0912** [bartwesselink/cordova-plugin-siri-shortcuts#15]
Hi,

I am having issues in generating the iOS build using this plugin. 

In error logs it says :
_Error: Version of installed plugin: "cordova-plugin-add-swift-support@1.7.0" does not satisfy dependency plugin requirement "cordova-plugin-add-swift-support@^1.7.2". Try --force to use installed plugin as dependency._

Please find in the attachment for complete error log.
[iOSBuildLog.txt](https://github.com/bartwesselink/cordova-plugin-siri-shortcuts/files/3225998/iOSBuildLog.txt)

**Comment by shreyasb0912** [comment]
Anybody facing this issue???

**Comment by RomanovX** [comment]
This means that another plugin of yours has a dependency on a highter version of the swift support plugin. Simply edit the package.json so it says `version=^1.7.2`
