### ISSUE TITLE
Argument labels '(rawValue:)' do not match any available overloads

### ISSUE THREAD

**Issue by haydarai** [bartwesselink/cordova-plugin-siri-shortcuts#2]
I initialize my ionic project using the ionic starter app. And then add SiriShortcuts plugin based on this documentation https://ionicframework.com/docs/native/siri-shortcuts/.

I tried `ionic serve -c`, the app works, but when I try to use the plugin, it says

```
Ionic Native: tried calling SiriShortcuts.donate, but the SiriShortcuts plugin is not installed.
Install the SiriShortcuts plugin: 'ionic cordova plugin add cordova-plugin-siri-shortcuts'
```

While I actually already install it, I even do the suggested command again to make sure that I've install it and it's still not working.

So I thought is it only able to be run if compiled through XCode 10 Beta? Then I run `ionic cordova build ios --prod`, open the xcodeproj file, and press the play button. Then when it try to build it, it return me this error.

![image](https://user-images.githubusercontent.com/2961388/44454167-613e1d80-a62d-11e8-86dc-915763007421.png)

Any idea what happened? I'm using XCode Beta 6 if you're wondering

**Comment by bartwesselink** [comment]
I haven't had time to test it on the more recent beta's, but I will do this weekend. It is probably caused by changed APIs.

**Comment by bartwesselink** [comment]
I didn't have time to resolve this earlier, but it should be resolved now. Issue was caused by constructors that had changed over the more recent betas.

**Comment by haydarai** [comment]
awesome, thanks!
