### ISSUE TITLE
Failed to compile on xcode 10 although it is required?

### ISSUE THREAD

**Issue by kuriakinzeng** [bartwesselink/cordova-plugin-siri-shortcuts#3]
Thanks for creating this plugin! 

I am really excited to try it out. I understand that this plugin requires Xcode 10. However, I can’t compile any cordova app on Xcode 10, even barebones and without this plugin added. 

Can you tell us more how you manage to compile? Thank you so much.

Xcode version: 10.0 beta 6
Cordova version: 8.0.0

Output when I run cordova run ios:

```
Building for iPhone X Simulator
Building project: /Users/k/Developer/learn/onsenshortcuts/platforms/ios/Siri Shorcuts.xcworkspace
	Configuration: Debug
	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/k/Developer/learn/onsenshortcuts/platforms/ios/build/emulator
    SDKROOT = iphonesimulator12.0
    SHARED_PRECOMPS_DIR = /Users/k/Developer/learn/onsenshortcuts/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/k/Developer/learn/onsenshortcuts/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

No target specified for emulator. Deploying to iPhone-X, 12.0 simulator
/Users/k/Developer/learn/onsenshortcuts/platforms/ios/build/emulator/Siri Shorcuts.app/Info.plist file not found.
```

**Comment by bartwesselink** [comment]
I can confirm this issue, even with this plugin not installed indeed. If I create a project without any plugins, I am still not able to run this command. This looks like a Cordova issue.

I do am able to compile this if I open the XCode-project in `/platforms/ios` manually in XCode and press compile.

**Comment by RasimKanca** [comment]
This is a known issue with Cordova and Xcode 10, you can [find more information about it here](https://github.com/apache/cordova-ios/issues/407) and a temporary workaround is also available in the comments.

**Comment by ShehryarAhmed** [comment]
try this
# Cordova CLI
cordova run ios --buildFlag='-UseModernBuildSystem=0'
cordova build ios --buildFlag='-UseModernBuildSystem=0'

# Ionic CLI
ionic cordova run ios -- --buildFlag="-UseModernBuildSystem=0"
ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"
