### ISSUE TITLE
Adding a Siri shortcut seems to work occasionally

### ISSUE THREAD

**Issue by rwbr** [bartwesselink/cordova-plugin-siri-shortcuts#7]
Of course I know, the plugin is still in Beta state!
However, in my project I try to add Siri Shortcuts for each favorite contact that I retrieve from an API. I try to add them like this: 

```typescript
if (platform.is('ios')) {
    if (this.favorites.length) {
    for (const fav of this.favorites) {
        console.log('## Add Siri Shortcut ', fav.displayName);
        let caption = fav.displayName + ' anrufen';
        this.siriShortcuts.donate({
        persistentIdentifier: caption,
        title: caption,
        suggestedInvocationPhrase: caption,
        userInfo: { uid: fav.uid },
        isEligibleForSearch: true,
        isEligibleForPrediction: true
        })
        .then(() => console.log('Shortcut donated.'))
        .catch((error: any) => console.error(error));
    }
    } else {
    this.siriShortcuts.removeAll();
    }
}
```

My environment:

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/ralfweinbrecher/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/ralfweinbrecher/Library/Android/sdk/)
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.3 (/Users/ralfweinbrecher/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 5.6.0
   OS                : macOS
   Xcode             : Xcode 10.0 Build version 10A254a
```

In my demo application there should be 4 favorite contacts, but under the Siri section of the iPhone settings there appear two shortcuts (sometimes there additionally re-appears an entry corresponding to a favorite that was deleted, it's an old entry added in an earlier stage of development).

What am I doing wrong? Is it bad practice to add these shortcuts iteratively? Does the plugin support dynamically created shortcuts?

**Comment by bartwesselink** [comment]
I am not sure what causes this. It is possible that there is a limit to the amount of shortcuts you can add to an NSUserActivity, I cannot find it stated anywhere. It should be no problem at all to create shortcuts dynamically. 

If there is a limit to the amount of shortcuts to an NSUserActivity, it is very hard to fix because it'd mean that the shortcuts cannot be added dynamically as they have to be defined in the building stage.

**Comment by rwbr** [comment]
I supposed something like that. I will study the documents. Maybe I find a clue. Thank you.
